# Generated by Django 5.1.2 on 2024-11-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0001_initial'),
        ('clientes', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviao',
            name='avi_grupo',
        ),
        migrations.AddField(
            model_name='aviao',
            name='cli_nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avioes_cliente', to='clientes.cliente'),
        ),
    ]
