# Generated by Django 5.1.3 on 2024-11-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviao',
            name='avi_codigo',
            field=models.CharField(default='DEFAULT', max_length=50),
        ),
    ]
