# Generated by Django 5.1.2 on 2024-11-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviao',
            name='avi_prefixo_do_aviao',
            field=models.CharField(max_length=10),
        ),
    ]
