# Generated by Django 5.1.2 on 2024-11-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviao',
            name='avi_grupo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aviao',
            name='avi_prefixo_do_aviao',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aviao',
            name='avi_toneladas',
            field=models.FloatField(),
        ),
    ]
