# Generated by Django 5.1.2 on 2024-11-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0002_alter_aviao_avi_prefixo_do_aviao'),
        ('avioes', '0002_alter_aviao_usuario'),
    ]

    operations = [
    ]
