# Generated by Django 5.1.2 on 2024-11-28 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0002_alter_aviao_avi_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aviao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avioes.aviao')),
            ],
        ),
    ]
