# Generated by Django 5.1.3 on 2024-11-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0002_aviao_avi_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviao',
            name='avi_codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
