# Generated by Django 5.1.3 on 2024-11-30 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0003_alter_aviao_avi_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviao',
            name='id',
        ),
        migrations.AddField(
            model_name='aviao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aviao',
            name='avi_codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aviao',
            name='avi_grupo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aviao',
            name='avi_prefixo_do_aviao',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aviao',
            name='avi_toneladas',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
