# Generated by Django 5.1.2 on 2024-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0005_alter_aviao_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aviao',
            name='id',
        ),
        migrations.AlterField(
            model_name='aviao',
            name='avi_codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
