# Generated by Django 5.1.2 on 2024-11-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lembrete',
            table='paginas_lembrete',
        ),
    ]
