# Generated by Django 5.1.2 on 2024-11-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_lembrete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='lembrete',
            name='data',
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='lembrete',
            table=None,
        ),
    ]
