# Generated by Django 5.1.3 on 2024-11-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_cliente_tarifa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarifa',
        ),
    ]
