# Generated by Django 5.1.3 on 2024-11-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_delete_tarifa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_preferencia', models.CharField(choices=[('PATIO', 'Pátio'), ('HANGAR', 'Hangar')], max_length=10)),
                ('valor_domestico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_internacional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grupo', models.CharField(choices=[('I', 'Grupo I'), ('II', 'Grupo II')], max_length=10)),
                ('tonelada_maxima', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
