# Generated by Django 5.1.3 on 2024-11-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_atividade_evento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
