# Generated by Django 5.1.2 on 2024-11-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0010_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
