# Generated by Django 3.2.8 on 2023-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, default='', max_length=250, verbose_name='Descrição')),
                ('obs', models.CharField(blank=True, default='', max_length=50, verbose_name='OBS')),
                ('relevancia', models.IntegerField(default=1, verbose_name='Relevância')),
                ('data', models.DateField()),
            ],
        ),
    ]
