# Generated by Django 4.2.2 on 2023-08-26 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0002_rename_atividade_lembrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lembrete',
            name='relevancia',
            field=models.IntegerField(default=1, verbose_name='Grau de Relevância'),
        ),
    ]
