# Generated by Django 5.1.2 on 2024-11-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
