# Generated by Django 5.1.2 on 2024-11-15 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0001_initial'),
        ('clientes', '0004_remove_cliente_cli_avi_codigo_cliente_avi_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='avi_codigo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cli_avi_codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='avioes.aviao'),
        ),
    ]
