# Generated by Django 5.1.3 on 2024-11-09 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, default='', max_length=250, verbose_name='Descrição')),
                ('obs', models.CharField(blank=True, default='', max_length=50, verbose_name='OBS')),
                ('relevancia', models.IntegerField(default=1, verbose_name='Grau de Relevância')),
                ('data', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
