# Generated by Django 5.1.2 on 2024-11-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lembretes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lembrete',
            options={'ordering': ['-relevancia']},
        ),
    ]
