# Generated by Django 5.0.4 on 2024-10-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_cliente',
            new_name='cli_nome',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cli_avi_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='avioes.aviao'),
        ),
    ]
