# Generated by Django 5.1.2 on 2024-11-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cobranca', models.CharField(max_length=20)),
                ('codigo_tarifa', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('codigo_aviao', models.CharField(max_length=20)),
            ],
        ),
    ]
