# Generated by Django 5.1.2 on 2024-11-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avioes', '0001_initial'),
        ('tarifas', '0003_alter_tarifa_tar_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cob_codigo', models.CharField(max_length=10)),
                ('quantidade_horas', models.PositiveIntegerField()),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avi_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='avioes.aviao')),
                ('tar_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifas.tarifa')),
            ],
        ),
    ]
