# Generated by Django 5.1.2 on 2024-11-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='avi_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobrancas.aviao'),
        ),
    ]
