# Generated by Django 5.1.3 on 2024-11-14 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('tar_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tar_tipo', models.CharField(max_length=255)),
                ('tar_valor_domestico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tar_valor_internacional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tar_grupo', models.IntegerField()),
                ('tar_ton_min', models.IntegerField()),
                ('tar_ton_max', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='cobranca',
            old_name='codigo_aviao',
            new_name='avi_codigo',
        ),
        migrations.RenameField(
            model_name='cobranca',
            old_name='codigo_cobranca',
            new_name='cob_codigo',
        ),
        migrations.RenameField(
            model_name='cobranca',
            old_name='quantidade',
            new_name='quantidade_horas',
        ),
        migrations.RenameField(
            model_name='cobranca',
            old_name='codigo_tarifa',
            new_name='tar_codigo',
        ),
        migrations.RenameField(
            model_name='cobranca',
            old_name='total',
            new_name='valor_total',
        ),
        migrations.CreateModel(
            name='Aviao',
            fields=[
                ('avi_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('avi_prefixo_do_aviao', models.CharField(max_length=50)),
                ('avi_toneladas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avi_grupo', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
