# Generated by Django 5.1.3 on 2024-12-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='campo_temporario',
            field=models.CharField(default='teste', max_length=100),
        ),
    ]
