# Generated by Django 5.1.2 on 2024-11-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0001_initial'),
        ('cobrancas', '0002_alter_cobranca_avi_codigo'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='avi_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avioes.aviao'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='tar_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifas.tarifa'),
        ),
        migrations.DeleteModel(
            name='Aviao',
        ),
        migrations.DeleteModel(
            name='Tarifa',
        ),
    ]
