# Generated by Django 5.1.2 on 2024-11-26 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avioes', '0001_initial'),
        ('cobrancas', '0003_alter_cobranca_avi_codigo_alter_cobranca_tar_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='avi_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='avioes.aviao'),
        ),
    ]
