# Generated by Django 5.1.2 on 2024-10-29 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('tar_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tar_tipo', models.CharField(max_length=255)),
                ('tar_valor_domestico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tar_valor_internacional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tar_grupo', models.IntegerField()),
                ('tar_ton_min', models.IntegerField()),
                ('tar_ton_max', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
