# Generated by Django 5.1.3 on 2024-11-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='tar_tipo',
            field=models.CharField(choices=[('Embarque', 'Tarifa de Embarque'), ('Desembarque', 'Tarifa de Desembarque'), ('Manuseio', 'Tarifa de Manuseio'), ('Armazenagem', 'Tarifa de Armazenagem'), ('Excesso', 'Tarifa por Excesso de Peso')], max_length=255),
        ),
    ]
