# Generated by Django 5.1.3 on 2024-11-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0002_alter_tarifa_tar_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='tar_tipo',
            field=models.CharField(max_length=255),
        ),
    ]
