# Generated by Django 5.1.3 on 2024-11-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0003_alter_tarifa_tar_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='tar_grupo',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tar_codigo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tar_tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tar_ton_max',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tar_ton_min',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
