# Generated by Django 5.1.3 on 2024-12-03 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas', '0004_remove_tarifa_tar_grupo_remove_tarifa_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='tar_grupo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tar_codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tar_tipo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tar_ton_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tar_ton_min',
            field=models.IntegerField(),
        ),
    ]
