# Generated by Django 5.1.2 on 2024-10-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('tar_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tar_tipo', models.CharField(max_length=255)),
                ('tar_valor_domestico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tar_valor_internacional', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tar_grupo', models.IntegerField()),
                ('tar_ton_min', models.IntegerField()),
                ('tar_ton_max', models.IntegerField()),
            ],
        ),
    ]
